spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show_sql: true
      format_sql: true
      use_sql_comments: true
  datasource:
    url: jdbc:mariadb://localhost:3306/wedding
    username: wedding
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    schemas: wedding
    enabled: true
    url: jdbc:mariadb://localhost:3306/wedding
    user: wedding
    password: 1234
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholder-replacement: false
    ignore-missing-migrations: true
    ignore-ignored-migrations: true
    ignore-future-migrations: true
