spring:
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      use_sql_comments: true

  datasource:
    url: jdbc:mariadb://localhost:3306/wedding
    username: wedding
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: true
    url: jdbc:mariadb://localhost:3306/wedding
    user: wedding
    password: 1234
    schemas: wedding
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholder-replacement: false
    ignore-missing-migrations: true
    ignore-ignored-migrations: true
    ignore-future-migrations: true

#logging:
#  level:
#    org:
#      springframework: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
